# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               roboTickle
tagline:             'Cluster Computing | Machine Learning'
description:         'Complete Notes on cluster computing <a href="https://twitter.com/sandeepkandekar></a>.'
url:                 http://robotickle.com
baseurl:             '/lanyon/'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/sandeepkandekar
  email:             sandeep.kandekar@gmail.com

# Custom vars
version:             1.0.0
