# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               roboTickle
tagline:             'Cluster Computing | Machine Learning'
description:         'Research <a href="http://robotickle.com" target="_blank">kandekar</a>. sandeep kandekar <a href="https://twitter.com/sandeepkandekar" target="_blank">@skan</a>.'
url:                 http://robotickle.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Sandeep Kandekar
  url:               https://twitter.com/sandeepkandekar
  email:             sandeep.kandekar@gmail.com

# Custom vars
version:             1.0.0
